INSERT INTO organizers (name, description, email, logourl) VALUES
                        ('Organizer 1', 'Description for Organizer 1', 'organizer1@example.com', 'http://example.com/logo1.png'),
                        ('Organizer 2', 'Description for Organizer 2', 'organizer2@example.com', 'http://example.com/logo2.png'),
                        ('Organizer 3', 'Description for Organizer 3', 'organizer3@example.com', 'http://example.com/logo3.png'),
                        ('Organizer 4', 'Description for Organizer 4', 'organizer4@example.com', 'http://example.com/logo4.png'),
                        ('Organizer 5', 'Description for Organizer 5', 'organizer5@example.com', 'http://example.com/logo5.png'),
                        ('Organizer 6', 'Description for Organizer 6', 'organizer6@example.com', 'http://example.com/logo6.png'),
                        ('Organizer 7', 'Description for Organizer 7', 'organizer7@example.com', 'http://example.com/logo7.png'),
                        ('Organizer 8', 'Description for Organizer 8', 'organizer8@example.com', 'http://example.com/logo8.png'),
                        ('Organizer 9', 'Description for Organizer 9', 'organizer9@example.com', 'http://example.com/logo9.png'),
                        ('Organizer 10', 'Description for Organizer 10', 'organizer10@example.com', 'http://example.com/logo10.png');
